apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-project1
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
        - name: web
          image: 654291821407.dkr.ecr.us-east-1.amazonaws.com/project-1:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20

