apiVersion: v1
kind: Service
metadata:
  name: flask-web-svc
  namespace: project1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: flask-web
  ports:
    - name: http
      port: 80
      targetPort: 8080

