apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-web-project-1.fullname" . }}
  labels: {{- include "flask-web-project-1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "flask-web-project-1.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

